---
# tasks file for zsh
- name: ~/Tools dir
  file: path={{ tools_path | expanduser }} state=directory
- name: ~/bin dir
  file: path={{ bin_path | expanduser }} state=directory
- name: required apt packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - vim
    - tmux
    - zsh
    - ack-grep
    - curl

- name: clone antigen.zsh repo
  git: repo=https://github.com/zsh-users/antigen.git dest={{ tools_path }}/antigen force=no update=no

- name: Clone dotfiles repo
  git: repo={{ dotfiles_repo }} dest={{ dotfiles_path }} accept_hostkey=yes force=no update=no

- name: list dotfiles/home
  command: ls -A {{ dotfiles_path | expanduser }}/home
  register: dotfiles

- name: list dotfiles/config
  command: ls -A {{ dotfiles_path | expanduser }}/config
  register: configfiles 

- name: list dotfiles/bin
  command: ls -A {{ dotfiles_path | expanduser }}/bin
  register: binfiles

- name: link dotfiles
  file: src={{ dotfiles_path | expanduser }}/home/{{ item }} dest=/home/{{ ansible_user_id }}/{{ item }} state=link force=yes
  with_items: "{{ dotfiles.stdout_lines }}"

- name: link dotfile/bin
  file: src={{ dotfiles_path | expanduser }}/bin/{{ item }} dest=/home/{{ ansible_user_id }}/bin/{{ item }} state=link force=yes
  with_items: "{{ binfiles.stdout_lines }}"

- name: link dotfiles/config
  file: src={{ dotfiles_path | expanduser }}/config/{{ item }} dest=/home/{{ ansible_user_id }}/.config/{{ item }} state=link force=yes
  with_items: "{{ configfiles.stdout_lines }}"

- name: change shell to zsh
  sudo: yes
  user: name={{ ansible_user_id }} shell=/usr/bin/zsh  state=present

